---
title: "leasing cleaning"
format: html
editor: visual
---

In this data notebook I will be analyzing GSA data that contains information regarding lease start and expiration dates, locations and representative info.

## Major Findings

-   

```{r}
#load libraries
library(tidyverse)
library(janitor)
library(dplyr)
library(DT)
```

```{r}
#Cleaning
dc <- read.csv("data/dc.csv") %>% 
  clean_names()
maryland <- read.csv("data/maryland.csv") %>% 
  clean_names()
#Only leases
dc_lease <- dc %>% 
  filter(occupancy_right_desc=="Leased")
maryland_lease <- maryland %>% 
  filter(occupancy_right_desc=="Leased")
```

I am now focusing on getting rid of the repeated rows of information that is found in both data sets.

```{r}
#getting rid of unecessary rows
dc_lease_cleaned <- dc_lease %>% 
 select(-c(walk_score,transit_score,representative_url,senator1_url,senator2_url)) 
maryland_lease_cleaned <- maryland_lease %>% 
   select(-c(walk_score,transit_score,representative_url)) 
#getting rid of the blanks in the final column
dc_lease_cleaned<- dc_lease_cleaned %>%
  filter(lease_num != "")
maryland_lease_cleaned <-maryland_lease_cleaned %>% 
  filter(lease_num != "")
```

These are the cleaned data tables that can be scrolled through and has a search button.

```{r}
datatable(maryland_lease_cleaned,  options = list(
  scrollX = TRUE,  # Enables horizontal scrolling
  autoWidth = TRUE # Adjusts column widths automatically
))
```

```{r}
datatable(dc_lease_cleaned,  options = list(
  scrollX = TRUE,  # Enables horizontal scrolling
  autoWidth = TRUE # Adjusts column widths automatically
))
```
